package com.banvien.fc.common.enums;

/**
 * Created by son.nguyen on 7/7/2020.
 */
public enum ErrorCodeMap {
    FAILURE_EXCEPTION(-1),
    FAILURE_PHONE_EXISTED(1),
    FAILURE_FULLNAME_EMPTY(2),
    FAILURE_GENDER_EMPTY(3),
    FAILURE_PHONE_EMPTY(4),
    FAILURE_PASSWORD_EMPTY(5),
    FAILURE_USER_EXISTED(6),
    FAILURE_INVALID_PHONE(7),
    FAILURE_INVALID_EMAIL(8),
    FAILURE_USER_ID_EMPTY(9),
    FAILURE_NOT_FULL_QUESTION(10),
    FAILURE_TOKEN_INVALID(11),
    FAILURE_EMAIL_EMPTY(12),
    FAILURE_RETYPEPASSWORD_NOTMATCH_PASSWORD(13),
    FAILURE_INVALID_ORG_BUSINESS_TYPE(14),
    FAILURE_LOGON_ID_EMPTY(15),
    FAILURE_INVALID_LOGON_ID(16),
    FAILURE_INVALID_INPUT_PARAM(17),
    FAILURE_INVALID_PASSWORD(18),
    FAILURE_WRONG_PASSWORD(19),
    FAILURE_COUNTRY_ID_EMPTY(20),
    FAILURE_CITY_ID_EMPTY(21),
    FAILURE_STATE_ID_EMPTY(22),
    FAILURE_ADDRESS_EMPTY(23),
    FAILURE_BUSINESS_TYPE_EMPTY(24),
    FAILURE_EMAIl_EXISTED(25),
    FAILURE_INVALID_STORE(26),
    FAILURE_INVALID_OTP_EXPIRE(27),
    FAILURE_INVALID_OTP_VALUE(28),
    FAILURE_DEGREE_EMPTY(29),
    FAILURE_CAREER_EMPTY(30),
    FAILURE_IDENTITY_NUMBER_EMPTY(31),
    FAILURE_MARRIED_EMPTY(32),
    FAILURE_INVALID_ORDER(33),
    FAILURE_INVALID_ORGANIZATION(34),
    FAILURE_NEED_CONTRACT(35),
    FAILURE_INVALID_CONTRACT_STATE(36),
    FAILURE_INVALID_ORDER_STATUS(37),
    FAILURE_PERMISSION_DENY(38),
    FAILURE_SURVEY_COMPLETED(39),
    FAILURE_PRODUCT_EMPTY(40),
    FAILURE_DELIVERY_METHOD_EMPTY(41),
    FAILURE_PAYMENT_METHOD_EMPTY(42),
    FAILURE_INVALID_ADDRESS(43),
    FAILURE_INVALID_EASY_ORDER(44),
    FAILURE_SHOPPING_CART_EMPTY(45),
    FAILURE_DELIVERY_MULTI_CITIES(46),
    FAILURE_GRAB_INIT_AUTHEN(47),
    FAILURE_PARSE_EASYORDERDTO(48),
    FAILURE_MISSING_GRAB_CERTIFICATES(49),
    FAILURE_MISSING_GRAB_REQUEST_BODY(50),
    FAILURE_NULL_ORDERCODE(51),
    FAILURE_NULL_GRAB_PAID_SAVE(52),
    FAILURE_CALCULATE_DISTANCE(53),
    PRODUCT_NOT_SALE_ONLINE_MODE(54)

    ;
    private final int value;
    ErrorCodeMap(int value){
        this.value = value;
    }
    public int getValue() {
        return value;
    }
}
